# Generated by Django 4.2.6 on 2023-11-07 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('species', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CropCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('office_contact', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('symbol', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Zilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('office_contact', models.CharField(max_length=16)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_agriculture.division')),
            ],
        ),
        migrations.CreateModel(
            name='ZillaCropFertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.FloatField(default=0.0)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_agriculture.crop')),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_agriculture.fertilizer')),
                ('zilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_agriculture.zilla')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=512)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zilla', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='smart_agriculture.zilla')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('body', models.TextField(blank=True)),
                ('post_date', models.DateTimeField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_agriculture.cropcategory'),
        ),
    ]
