# Generated by Django 4.2.6 on 2023-11-07 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smart_agriculture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='smart_agriculture.cropcategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
