# Generated by Django 4.2.6 on 2023-11-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_agriculture', '0002_alter_crop_crop_category_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zilla',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zillas', to='smart_agriculture.division'),
        ),
    ]
