# Generated by Django 4.2.6 on 2023-11-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_agriculture', '0006_alter_zillacropfertilizer_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
