# Generated by Django 4.2.6 on 2023-11-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_agriculture', '0007_post_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_date']},
        ),
    ]
